### ISSUE TITLE
[Suggestion] (Local Youtube Downloader) Generate video(s) without the sponsorships

### ISSUE THREAD

**Issue by TheAlienDrew** [maple3142/browser-extensions#18]
It's a long shot I know, but there is already an extension out there doing a pretty great job at skipping ADs and other such stuff that video creators include in their videos. Being able to download videos from YouTube is great, but wouldn't you say it could be better if you could download some without the sponsors included?

I suggest looking into maybe using some SponsorBlock APIs (https://github.com/ajayyy/SponsorBlock) as it would prove most useful for what I imagine most of the user base is for the script you provide.

**Comment by maple3142** [comment]
It isn't easily doable.
