### ISSUE TITLE
[Enhancement] Downloading VP9 or AV1 video and OPUS audio when available at 1080p (or lower) source

### ISSUE THREAD

**Issue by Aesis7271** [maple3142/browser-extensions#19]
So far this wasn't an issue for me since I've always been using the manual link downloads, but the manual link downloads are now throttled since a few days while the one click download isn't, which is why I'm proposing this enhancement.
It would be nice to be able to get the higher quality codecs (when available) when the source video is 1080p (or lower) when using the one click download. The one click download only downloads AVC (x264) video and MP3 audio even when VP9 or AV1 video and OPUS audio is available. I tried editing the script by changing
`x.mimeType.includes('video/mp4')`
to
`x.mimeType.includes('video/webm')`
for both video and audio, and while the video is correctly downloaded in VP9, the audio is being downloaded in the lowest OPUS quality. This is (probably) because the script takes the first OPUS codec from the `itag` list , which is sorted in ascending order, and the highest quality OPUS audio is the highest ID from the list (in this case, `itag=251`).
My coding knowledge is rather limited so I'm not able to go much further by myself, but maybe the script can be made to take the highest `itag` from the audio and video list respectively (since this is also the case for video side, where the `itag`s are in ascending order of AVC<VP9<AV1 within the same resolution and framerate), or to sort by descending order instead.
Note that the video is downloaded in VP9 when the source is >1080p (since such sources don't have AVC encoding)

**Comment by maple3142** [comment]
> but the manual link downloads are now throttled since a few days while the one click download isn't

It can be sped up by using a multi-thread downloader such as [IDM](https://www.internetdownloadmanager.com/), [aria2](https://aria2.github.io/) or whatever.


I choose x264 on purpose because it is more widely supported across platforms and applications. If you want that, you can edit it yourself or use [youtube-dl](https://youtube-dl.org/).

**Comment by Aesis7271** [comment]
> It can be sped up by using a multi-thread downloader such as [IDM](https://www.internetdownloadmanager.com/), [aria2](https://aria2.github.io/) or whatever.
I don't think it has to do with mutithreading at all, it's the download behavior that changed, I was previously able to get 3MB/s per item, I'm now getting 2MB/burst (every 5-10 seconds) with nothing in between.

I'll see what I can do to edit it myself

**Comment by maple3142** [comment]
> I don't think it has to do with mutithreading at all

It is. One click download is slow when I didn't implement multi-thread downloading, and it becomes much faster after.

**Comment by Aesis7271** [comment]
> > I don't think it has to do with mutithreading at all
> 
> It is. One click download is slow when I didn't implement multi-thread downloading, and it becomes much faster after.

So why were the links working fine just a few days ago?
