### ISSUE TITLE
You should never eval, every eval is vulnerability.

### ISSUE THREAD

**Issue by KOLANICH** [maple3142/browser-extensions#21]
If you want to parse JS literal stuff, you can transform it into JSON using a regex and then parse that JSON.

**Comment by maple3142** [comment]
But it is not parsing JSON, it is actual running Javascript code from string

**Comment by maple3142** [comment]
https://github.com/maple3142/browser-extensions/blob/9aa12f515b4692237967caea8a556bb20786c288/scripts/local-youtube-dl.user.js#L185 I think you mean this right?

**Comment by KOLANICH** [comment]
not quite.

https://github.com/maple3142/browser-extensions/blob/9aa12f515b4692237967caea8a556bb20786c288/scripts/local-youtube-dl.user.js#L618

**Comment by maple3142** [comment]
It is not json, and it is easier to use eval to parse a malformed json
