### ISSUE TITLE
pixiv-original-image and pximg-403-forbidden-fix can probably be replaced by maxurl

### ISSUE THREAD

**Issue by jloqfjgk** [maple3142/browser-extensions#23]
The open-source extension [1] [Image Max URL](https://github.com/qsniyg/maxurl) supports Pixiv and inserts correct referrer when necessary, not to mention that it supports many other websites as well.

[1] Userscript version is also available.

-----

Image Max URL 是開放源代碼的外掛（瀏覽器擴充功能），除了支援 Pixiv ，也支援其他網站，讓用戶可以找到高畫質原圖。

（註：本人並非 Image Max URL 的作者，只是想推介這個外掛，讓用戶可以不用分別尋找及安裝各個網站專用的 Userscript 或外掛。）

**Comment by maple3142** [comment]
只是這個和這個 repo 無關，就關閉了
